In [1]:
import numpy as np
import pandas as pd

data = np.array(
    [
        [4, 3, 2],
        [4, 4, 2],
        [3, 3, 3],
        [4, 2, 2],
    ]
)

In [2]:
bobot = [0.3, 0.45, 0.25]
tipe = ["benefit", "cost", "cost"]

print("Bobot Kriteria :", bobot)
print("Tipe Kriteia :", tipe)

Bobot Kriteria : [0.3, 0.45, 0.25]
Tipe Kriteia : ['benefit', 'cost', 'cost']


In [3]:
bobot_normal = [round(bobot[i] / sum(bobot), 4) for i in range(len(bobot))]
print("Hasil normalisasi bobot: ", bobot_normal)

Hasil normalisasi bobot:  [0.3, 0.45, 0.25]


In [4]:
normalisasi = data / np.sqrt(np.sum(data**2, axis=0))
print("hasil normalisasi kriteria: ", normalisasi)

hasil normalisasi kriteria:  [[0.52981294 0.48666426 0.43643578]
 [0.52981294 0.64888568 0.43643578]
 [0.39735971 0.48666426 0.65465367]
 [0.52981294 0.32444284 0.43643578]]


In [5]:
norm_terbobot = normalisasi * bobot_normal
print("Hasil normalisasi terbobot: ", norm_terbobot)

Hasil normalisasi terbobot:  [[0.15894388 0.21899892 0.10910895]
 [0.15894388 0.29199856 0.10910895]
 [0.11920791 0.21899892 0.16366342]
 [0.15894388 0.14599928 0.10910895]]


In [6]:
ideal_positif = []
ideal_negatif = []

for i in range(len(tipe)):
    max = norm_terbobot[:, i].max()
    min = norm_terbobot[:, i].min()
    if tipe[i] == "benefit":
        ideal_positif.append(max)
        ideal_negatif.append(min)
    else:
        ideal_positif.append(min)
        ideal_negatif.append(max)

print("Solusi ideal positif: ", ideal_positif)
print("Solusi ideal negatif: ", ideal_negatif)

Solusi ideal positif:  [np.float64(0.15894388284780525), np.float64(0.1459992790176863), np.float64(0.1091089451179962)]
Solusi ideal negatif:  [np.float64(0.11920791213585394), np.float64(0.2919985580353726), np.float64(0.1636634176769943)]


In [7]:
jarak_positif = np.sqrt(np.sum((norm_terbobot - ideal_positif) ** 2, axis=1))
jarak_negatif = np.sqrt(np.sum((norm_terbobot - ideal_negatif) ** 2, axis=1))
print("Jarak positif: ", jarak_positif)
print("Jarak negatif: ", jarak_negatif)

Jarak positif:  [0.07299964 0.14599928 0.09941874 0.        ]
Jarak negatif:  [0.09941874 0.06749176 0.07299964 0.16084442]


In [8]:
nilai_topsis = jarak_negatif / (jarak_positif + jarak_negatif)
rangking = np.argsort(nilai_topsis)[::-1]
print("Nilai TOPSIS: ", nilai_topsis)

print("Hasil peringkat")
for i, idx in enumerate(rangking):
    print(f"Alternatif {idx + 1}: {nilai_topsis[idx]}")

best_alternatif = rangking[0] + 1
print("\nAlternatif terbaik: ", best_alternatif)

Nilai TOPSIS:  [0.57661335 0.31613393 0.42338665 1.        ]
Hasil peringkat
Alternatif 4: 1.0
Alternatif 1: 0.5766133453917497
Alternatif 3: 0.42338665460825053
Alternatif 2: 0.3161339286455639

Alternatif terbaik:  4


In [9]:
nilai_topsis = jarak_positif / (jarak_positif + jarak_negatif)
rangking = np.argsort(nilai_topsis)
print("Nilai TOPSIS: ", nilai_topsis)

print("Hasil peringkat")
for i, idx in enumerate(rangking):
    print(f"Alternatif {idx + 1}: {nilai_topsis[idx]}")

best_alternatif = rangking[0] + 1
print("\nAlternatif terbaik: ", best_alternatif)

Nilai TOPSIS:  [0.42338665 0.68386607 0.57661335 0.        ]
Hasil peringkat
Alternatif 4: 0.0
Alternatif 1: 0.42338665460825037
Alternatif 3: 0.5766133453917495
Alternatif 2: 0.683866071354436

Alternatif terbaik:  4
