In [1]:
import numpy as np

alternatif = ["Faruq Regency", "Fakhri Regency", "Nafisa Regency", "Aisha Regency"]
kriteria = ["Lokasi", "Harga", "Desain", "Fasilitas"]

alternatif_kriteria = [
    [1, 1 / 2, 1 / 3, 1 / 5],
    [2, 1, 1 / 3, 1 / 4],
    [3, 3, 1, 1 / 2],
    [5, 4, 2, 1],
]

print(alternatif_kriteria)

[[1, 0.5, 0.3333333333333333, 0.2], [2, 1, 0.3333333333333333, 0.25], [3, 3, 1, 0.5], [5, 4, 2, 1]]


In [2]:
jumlah_sum = np.sum(alternatif_kriteria, axis=0)
print(jumlah_sum)

[11.          8.5         3.66666667  1.95      ]


In [3]:
normalisasi = alternatif_kriteria / jumlah_sum
print(normalisasi)

[[0.09090909 0.05882353 0.09090909 0.1025641 ]
 [0.18181818 0.11764706 0.09090909 0.12820513]
 [0.27272727 0.35294118 0.27272727 0.25641026]
 [0.45454545 0.47058824 0.54545455 0.51282051]]


In [4]:
prioritas = np.sum(normalisasi, axis=1).reshape(-1, 1)
print(prioritas)


[[0.34320581]
 [0.51857946]
 [1.15480598]
 [1.98340875]]


In [5]:
bobot_kriteria = prioritas / np.sum(prioritas)
print(bobot_kriteria)


[[0.08580145]
 [0.12964486]
 [0.28870149]
 [0.49585219]]


In [6]:
eigen_value = bobot_kriteria * jumlah_sum.reshape(-1, 1)
print(eigen_value)

total_eigen = np.sum(eigen_value)
print(total_eigen)

[[0.94381599]
 [1.10198135]
 [1.05857215]
 [0.96691176]]
4.07128125142831


In [7]:
n = len(kriteria)
random_index = {
    1: 0,
    2: 0,
    3: 0.58,
    4: 0.9,
    5: 1.12,
    6: 1.24,
    7: 1.32,
    8: 1.41,
    9: 1.45,
    10: 1.49,
}

CI = (total_eigen - n) / (n - 1)
RI = random_index[n]

CR = CI / RI
print(CR)

0.026400463491966703


In [8]:
if CR <= 0.1:
    print("Konsisten (CR<=0.1)")
else:
    print("Tidak Konsisten (CR>0.1)")

Konsisten (CR<=0.1)


In [9]:
alternatif_lokasi = [
    [1, 1 / 3, 1 / 3, 1 / 3],
    [3, 1, 1, 2],
    [3, 1, 1, 1],
    [3, 1 / 2, 1 / 2, 1],
]

jumlah_sum_lokasi = np.sum(alternatif_lokasi, axis=0)
normalisasi_lokasi = alternatif_lokasi / jumlah_sum_lokasi
prioritas_lokasi = np.sum(normalisasi_lokasi, axis=1).reshape(-1, 1)

bobot_lokasi = prioritas_lokasi / np.sum(prioritas_lokasi)
print(bobot_lokasi)

[[0.1030543]
 [0.3668552]
 [0.3091629]
 [0.2209276]]


In [10]:
alternatif_harga = [
    [1, 1 / 3, 1 / 4, 1 / 3],
    [3, 1, 1, 1 / 2],
    [4, 1, 1, 1 / 2],
    [3, 2, 2, 1],
]

jumlah_sum_harga = np.sum(alternatif_harga, axis=0)
normalisasi_harga = alternatif_harga / jumlah_sum_harga
prioritas_harga = np.sum(normalisasi_harga, axis=1).reshape(-1, 1)

bobot_harga = prioritas_harga / np.sum(prioritas_harga)
print(bobot_harga)

[[0.09237821]
 [0.23826908]
 [0.26099636]
 [0.40835635]]


In [11]:
alternatif_desain = [
    [1, 1 / 5, 1 / 4, 1 / 4],
    [5, 1, 2 / 3, 2],
    [4, 1.5, 1, 2],
    [4, 1 / 2, 1 / 2, 1],
]

jumlah_sum_desain = np.sum(alternatif_desain, axis=0)
normalisasi_desain = alternatif_desain / jumlah_sum_desain
prioritas_desain = np.sum(normalisasi_desain, axis=1).reshape(-1, 1)

bobot_desain = prioritas_desain / np.sum(prioritas_desain)
print(bobot_desain)

[[0.07124897]
 [0.33161433]
 [0.38730244]
 [0.20983426]]


In [12]:
alternatif_fasilitas = [
    [1, 5, 5, 4],
    [1 / 5, 1, 1, 2],
    [1 / 5, 1, 1, 2],
    [1 / 4, 1 / 2, 1 / 2, 1],
]

jumlah_sum_fasilitas = np.sum(alternatif_fasilitas, axis=0)
normalisasi_fasilitas = alternatif_fasilitas / jumlah_sum_fasilitas
prioritas_fasilitas = np.sum(normalisasi_fasilitas, axis=1).reshape(-1, 1)

bobot_fasilitas = prioritas_fasilitas / np.sum(prioritas_fasilitas)
print(bobot_fasilitas)

[[0.5959596 ]
 [0.15252525]
 [0.15252525]
 [0.0989899 ]]


In [13]:
bobot_kali = [
    bobot_lokasi * bobot_kriteria[0],
    bobot_harga * bobot_kriteria[1],
    bobot_desain * bobot_kriteria[2],
    bobot_fasilitas * bobot_kriteria[3],
]

bobot_kali = np.array(bobot_kali)
bobot_kali

array([[[0.00884221],
        [0.03147671],
        [0.02652663],
        [0.01895591]],

       [[0.01197636],
        [0.03089036],
        [0.03383684],
        [0.0529413 ]],

       [[0.02056969],
        [0.09573755],
        [0.11181479],
        [0.06057946]],

       [[0.29550787],
        [0.07562998],
        [0.07562998],
        [0.04908436]]])

In [14]:
skor = np.sum(bobot_kali, axis=0)
skor

array([[0.33689612],
       [0.2337346 ],
       [0.24780824],
       [0.18156103]])

In [15]:
rangking = {
    alternatif[0]: skor[0],
    alternatif[1]: skor[1],
    alternatif[2]: skor[2],
    alternatif[3]: skor[3],
}

print("Rangking Terurut: ", rangking)

Rangking Terurut:  {'Faruq Regency': array([0.33689612]), 'Fakhri Regency': array([0.2337346]), 'Nafisa Regency': array([0.24780824]), 'Aisha Regency': array([0.18156103])}


In [16]:
sorted_rangking = sorted(rangking.items(), key=lambda x: x[1], reverse=True)
print("rangking terurut: ", sorted_rangking)
print(
    "Perusahaan terpilih adalah:",
    sorted_rangking[0][0],
    "dengan nilai ",
    sorted_rangking[0][1],
)

rangking terurut:  [('Faruq Regency', array([0.33689612])), ('Nafisa Regency', array([0.24780824])), ('Fakhri Regency', array([0.2337346])), ('Aisha Regency', array([0.18156103]))]
Perusahaan terpilih adalah: Faruq Regency dengan nilai  [0.33689612]
