In [1]:
import numpy as np

alternatif = ["CV Sejahtera", "CV Mandiri", "CV Bersama"]
kriteria = ["Harga", "Kualitas", "Waktu"]

alternatif_kriteria = [
    [1, 5, 7],
    [1 / 5, 1, 3],
    [1 / 7, 1 / 3, 1],
]

print(alternatif_kriteria)

[[1, 5, 7], [0.2, 1, 3], [0.14285714285714285, 0.3333333333333333, 1]]


In [2]:
jumlah_sum = np.sum(alternatif_kriteria, axis=0)
print(jumlah_sum)

[ 1.34285714  6.33333333 11.        ]


In [3]:
normalisasi = alternatif_kriteria / jumlah_sum
print(normalisasi)

[[0.74468085 0.78947368 0.63636364]
 [0.14893617 0.15789474 0.27272727]
 [0.10638298 0.05263158 0.09090909]]


In [4]:
prioritas = np.sum(normalisasi, axis=1).reshape(-1, 1)
print(prioritas)


[[2.17051817]
 [0.57955818]
 [0.24992365]]


In [5]:
bobot_kriteria = prioritas / np.sum(prioritas)
print(bobot_kriteria)


[[0.72350606]
 [0.19318606]
 [0.08330788]]


In [6]:
eigen_value = bobot_kriteria * jumlah_sum.reshape(-1, 1)
print(eigen_value)

total_eigen = np.sum(eigen_value)
print(total_eigen)

[[0.97156528]
 [1.22351171]
 [0.91638671]]
3.1114637011613495


In [7]:
n = len(kriteria)
random_index = {
    1: 0,
    2: 0,
    3: 0.58,
    4: 0.9,
    5: 1.12,
    6: 1.24,
    7: 1.32,
    8: 1.41,
    9: 1.45,
    10: 1.49,
}

CI = (total_eigen - n) / (n - 1)
RI = random_index[n]

CR = CI / RI
print(CR)

0.09608939755288752


In [8]:
if CR <= 0.1:
    print("Konsisten (CR<=0.1)")
else:
    print("Tidak Konsisten (CR>0.1)")

Konsisten (CR<=0.1)


In [9]:
alternatif_harga = [
    [1, 3, 3],
    [1 / 3, 1, 5],
    [1 / 3, 1 / 5, 1],
]

jumlah_sum_harga = np.sum(alternatif_harga, axis=0)
normalisasi_harga = alternatif_harga / jumlah_sum_harga
prioritas_harga = np.sum(normalisasi_harga, axis=1).reshape(-1, 1)

bobot_harga = prioritas_harga / np.sum(prioritas_harga)
print(bobot_harga)

[[0.54920635]
 [0.33121693]
 [0.11957672]]


In [10]:
alternatif_kualitas = [
    [1, 3, 3],
    [1 / 3, 1, 7],
    [1 / 3, 1 / 7, 1],
]

jumlah_sum_kualitas = np.sum(alternatif_kualitas, axis=0)
normalisasi_kualitas = alternatif_kualitas / jumlah_sum_kualitas
prioritas_kualitas = np.sum(normalisasi_kualitas, axis=1).reshape(-1, 1)

bobot_kualitas = prioritas_kualitas / np.sum(prioritas_kualitas)
print(bobot_kualitas)

[[0.5322884 ]
 [0.35924765]
 [0.10846395]]


In [11]:
alternatif_waktu = [
    [1, 3, 1],
    [1 / 3, 1, 5],
    [1, 1 / 5, 1],
]

jumlah_sum_waktu = np.sum(alternatif_waktu, axis=0)
normalisasi_waktu = alternatif_waktu / jumlah_sum_waktu
prioritas_waktu = np.sum(normalisasi_waktu, axis=1).reshape(-1, 1)

bobot_waktu = prioritas_waktu / np.sum(prioritas_waktu)
print(bobot_waktu)

[[0.42857143]
 [0.36507937]
 [0.20634921]]


In [12]:
bobot_kali = [
    bobot_harga * bobot_kriteria[0],
    bobot_kualitas * bobot_kriteria[1],
    bobot_waktu * bobot_kriteria[2],
]

bobot_kali = np.array(bobot_kali)
bobot_kali

array([[[0.39735412],
        [0.23963746],
        [0.08651448]],

       [[0.1028307 ],
        [0.06940164],
        [0.02095372]],

       [[0.03570338],
        [0.03041399],
        [0.01719052]]])

In [13]:
skor = np.sum(bobot_kali, axis=0)
skor

array([[0.5358882 ],
       [0.33945308],
       [0.12465872]])

In [14]:
rangking = {
    alternatif[0]: skor[0],
    alternatif[1]: skor[1],
    alternatif[2]: skor[2],
}

print("Rangking Terurut: ", rangking)

Rangking Terurut:  {'CV Sejahtera': array([0.5358882]), 'CV Mandiri': array([0.33945308]), 'CV Bersama': array([0.12465872])}


In [15]:
sorted_rangking = sorted(rangking.items(), key=lambda x: x[1], reverse=True)
print("rangking terurut: ", sorted_rangking)
print(
    "Perusahaan terpilih adalah:",
    sorted_rangking[0][0],
    "dengan nilai ",
    sorted_rangking[0][1],
)

rangking terurut:  [('CV Sejahtera', array([0.5358882])), ('CV Mandiri', array([0.33945308])), ('CV Bersama', array([0.12465872]))]
Perusahaan terpilih adalah: CV Sejahtera dengan nilai  [0.5358882]
